// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTkjyHz18uaCyMyXMMfsbVOLETs4K8rBQ',
    appId: '1:700589006061:web:a69d0157ea1f41819e40e4',
    messagingSenderId: '700589006061',
    projectId: 'bd-prueba-3aac5',
    authDomain: 'bd-prueba-3aac5.firebaseapp.com',
    storageBucket: 'bd-prueba-3aac5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsjKRhBtY3m0njTk_KT9qP0-7Os6rKrRc',
    appId: '1:700589006061:android:174c6e78910e128d9e40e4',
    messagingSenderId: '700589006061',
    projectId: 'bd-prueba-3aac5',
    storageBucket: 'bd-prueba-3aac5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMFe5xemPlBwsF3jeRUteFZa_mCc0VtbQ',
    appId: '1:700589006061:ios:bba64534416cfdc49e40e4',
    messagingSenderId: '700589006061',
    projectId: 'bd-prueba-3aac5',
    storageBucket: 'bd-prueba-3aac5.appspot.com',
    iosBundleId: 'com.example.tusCanchasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMFe5xemPlBwsF3jeRUteFZa_mCc0VtbQ',
    appId: '1:700589006061:ios:679f035bc24cf5f99e40e4',
    messagingSenderId: '700589006061',
    projectId: 'bd-prueba-3aac5',
    storageBucket: 'bd-prueba-3aac5.appspot.com',
    iosBundleId: 'com.example.tusCanchasApp.RunnerTests',
  );
}
